#!/usr/bin/env bash
# install ngix
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -y enable
sudo ufw allow 'Nginx HTTP'
sudo chmod o+w /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
