#!/usr/bin/env bash
# redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw -y enable
sudo ufw allow 'Nginx HTTP'
sudo chmod o+w /var/www/html/index.nginx-debian.html
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
