#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "26i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
service nginx restart
