#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    default_backend http_back
backend http_back
    balance roundrobin
    server 531338-web-01 54.197.21.225:80 check
    server 531338-web-02 52.87.255.100:80 check
EOF
sudo service haproxy restart
