#!/usr/bin/env bash
# Configures a server to listen on port 80.
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/site-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
