#!/usr/bin/env bash
# Displays some of the content of /etc/passwd

file="/etc/passwd"
while IFS=":" read -r username _ userid _ _ homedirectory _; do
	echo "$username:$userid:$homedirectory"
done < "$file"
