#!/usr/bin/env bash
# Displays some of the content of /etc/passwd

file="/etc/passwd"
while IFS=":" read -r username password userid groupid info homedirectory shell; do
	echo "The user $username is part of the $groupid gang, lives in $homedirectory and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < "$file"
