#!/usr/bin/env bash
# Writes a phrase ten times using while loop and another
#+ phrase in the middle

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	(( i++ ))
	if [ "$i" -eq 9 ]; then
		echo "Hi"
	fi
done
