#!/usr/bin/env bash
# Displays 12 hours and 59 minutes...literally

hours=0
until [ "$hours" -eq 13 ]
do
	minutes=1
	echo "Hour: $hours"
	until [ "$minutes" -eq 60 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hours++ ))
done
