#!/usr/bin/env bash
# Displays 12 hours and 59 minutes...literally

hours=0
while [ "$hours" -lt 13 ]
do
	minutes=1
	echo "Hour: $hours"
	while [ "$minutes" -lt 60 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	(( hours++ ))
done
