#!/usr/bin/env bash
# configures an Ubuntu server with special requirements
sudo cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$/127.0.0.2/g' ~/hosts.new
sed -i "\$a 8.8.8.8 facebook.com" ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
