#!/usr/bin/env bash
# configure Nginx to run as user nginx
pkill 'apache2'
chmod 0644 /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo --user nginx service nginx restart
